Repository libp2p/go-libp2p-pubsub-router, pull requests merged in 2018-09, with the labels that each got.

#8 Enable CI
  ci/Jenkinsfile
Labels: in progress

#9 gx update and fix code to use new Cid type
  .gx/lastpubver
  package.json
Labels: dependency-update, enhancement, in progress

#7 Implement SearchValue
  package.json
  pubsub.go
  pubsub_test.go
Labels: feature, in progress

#10 gx: update go-libp2p-routing
  .gx/lastpubver
  package.json
Labels: in progress

#11 gx publish 0.4.4
  .gx/lastpubver
  package.json
Labels: in progress

#12 Stop search after a good value is found
  .gx/lastpubver
  package.json
  pubsub.go
  pubsub_test.go
Labels: in progress
